/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as AuthCulturasRouteImport } from './routes/_auth/culturas'
import { Route as AuthPerfilRouteImport } from './routes/_auth/perfil'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AuthPropriedadesIndexRouteImport } from './routes/_auth/propriedades/index'
import { Route as AuthPropriedadesNovaRouteImport } from './routes/_auth/propriedades/nova'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as AuthPropriedadesPropertyIdIndexRouteImport } from './routes/_auth/propriedades/$propertyId/index'
import { Route as AuthPropriedadesPropertyIdCulturasNovaRouteImport } from './routes/_auth/propriedades/$propertyId/culturas/nova'
import { Route as AuthPropriedadesPropertyIdCulturasCropIdIndexRouteImport } from './routes/_auth/propriedades/$propertyId/culturas/$cropId/index'
import { Route as AuthPropriedadesPropertyIdCulturasCropIdRecomendacaoRouteImport } from './routes/_auth/propriedades/$propertyId/culturas/$cropId/recomendacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCulturasRoute = AuthCulturasRouteImport.update({
  id: '/culturas',
  path: '/culturas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPerfilRoute = AuthPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthRoute,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPropriedadesIndexRoute = AuthPropriedadesIndexRouteImport.update({
  id: '/propriedades/',
  path: '/propriedades/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPropriedadesNovaRoute = AuthPropriedadesNovaRouteImport.update({
  id: '/propriedades/nova',
  path: '/propriedades/nova',
  getParentRoute: () => AuthRoute,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPropriedadesPropertyIdIndexRoute =
  AuthPropriedadesPropertyIdIndexRouteImport.update({
    id: '/propriedades/$propertyId/',
    path: '/propriedades/$propertyId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthPropriedadesPropertyIdCulturasNovaRoute =
  AuthPropriedadesPropertyIdCulturasNovaRouteImport.update({
    id: '/propriedades/$propertyId/culturas/nova',
    path: '/propriedades/$propertyId/culturas/nova',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthPropriedadesPropertyIdCulturasCropIdIndexRoute =
  AuthPropriedadesPropertyIdCulturasCropIdIndexRouteImport.update({
    id: '/propriedades/$propertyId/culturas/$cropId/',
    path: '/propriedades/$propertyId/culturas/$cropId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthPropriedadesPropertyIdCulturasCropIdRecomendacaoRoute =
  AuthPropriedadesPropertyIdCulturasCropIdRecomendacaoRouteImport.update({
    id: '/propriedades/$propertyId/culturas/$cropId/recomendacao',
    path: '/propriedades/$propertyId/culturas/$cropId/recomendacao',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/culturas': typeof AuthCulturasRoute
  '/perfil': typeof AuthPerfilRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/propriedades/nova': typeof AuthPropriedadesNovaRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/propriedades/': typeof AuthPropriedadesIndexRoute
  '/propriedades/$propertyId/': typeof AuthPropriedadesPropertyIdIndexRoute
  '/propriedades/$propertyId/culturas/nova': typeof AuthPropriedadesPropertyIdCulturasNovaRoute
  '/propriedades/$propertyId/culturas/$cropId/recomendacao': typeof AuthPropriedadesPropertyIdCulturasCropIdRecomendacaoRoute
  '/propriedades/$propertyId/culturas/$cropId/': typeof AuthPropriedadesPropertyIdCulturasCropIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/culturas': typeof AuthCulturasRoute
  '/perfil': typeof AuthPerfilRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/propriedades/nova': typeof AuthPropriedadesNovaRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/propriedades': typeof AuthPropriedadesIndexRoute
  '/propriedades/$propertyId': typeof AuthPropriedadesPropertyIdIndexRoute
  '/propriedades/$propertyId/culturas/nova': typeof AuthPropriedadesPropertyIdCulturasNovaRoute
  '/propriedades/$propertyId/culturas/$cropId/recomendacao': typeof AuthPropriedadesPropertyIdCulturasCropIdRecomendacaoRoute
  '/propriedades/$propertyId/culturas/$cropId': typeof AuthPropriedadesPropertyIdCulturasCropIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_auth/culturas': typeof AuthCulturasRoute
  '/_auth/perfil': typeof AuthPerfilRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_auth/propriedades/nova': typeof AuthPropriedadesNovaRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/_auth/propriedades/': typeof AuthPropriedadesIndexRoute
  '/_auth/propriedades/$propertyId/': typeof AuthPropriedadesPropertyIdIndexRoute
  '/_auth/propriedades/$propertyId/culturas/nova': typeof AuthPropriedadesPropertyIdCulturasNovaRoute
  '/_auth/propriedades/$propertyId/culturas/$cropId/recomendacao': typeof AuthPropriedadesPropertyIdCulturasCropIdRecomendacaoRoute
  '/_auth/propriedades/$propertyId/culturas/$cropId/': typeof AuthPropriedadesPropertyIdCulturasCropIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/recuperar-senha'
    | '/culturas'
    | '/perfil'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/propriedades/nova'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/propriedades/'
    | '/propriedades/$propertyId/'
    | '/propriedades/$propertyId/culturas/nova'
    | '/propriedades/$propertyId/culturas/$cropId/recomendacao'
    | '/propriedades/$propertyId/culturas/$cropId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/recuperar-senha'
    | '/culturas'
    | '/perfil'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/propriedades/nova'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/propriedades'
    | '/propriedades/$propertyId'
    | '/propriedades/$propertyId/culturas/nova'
    | '/propriedades/$propertyId/culturas/$cropId/recomendacao'
    | '/propriedades/$propertyId/culturas/$cropId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/login'
    | '/recuperar-senha'
    | '/_auth/culturas'
    | '/_auth/perfil'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/_auth/propriedades/nova'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/_auth/propriedades/'
    | '/_auth/propriedades/$propertyId/'
    | '/_auth/propriedades/$propertyId/culturas/nova'
    | '/_auth/propriedades/$propertyId/culturas/$cropId/recomendacao'
    | '/_auth/propriedades/$propertyId/culturas/$cropId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/culturas': {
      id: '/_auth/culturas'
      path: '/culturas'
      fullPath: '/culturas'
      preLoaderRoute: typeof AuthCulturasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/perfil': {
      id: '/_auth/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthPerfilRouteImport
      parentRoute: typeof AuthRoute
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/propriedades/': {
      id: '/_auth/propriedades/'
      path: '/propriedades'
      fullPath: '/propriedades/'
      preLoaderRoute: typeof AuthPropriedadesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/propriedades/nova': {
      id: '/_auth/propriedades/nova'
      path: '/propriedades/nova'
      fullPath: '/propriedades/nova'
      preLoaderRoute: typeof AuthPropriedadesNovaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/propriedades/$propertyId/': {
      id: '/_auth/propriedades/$propertyId/'
      path: '/propriedades/$propertyId'
      fullPath: '/propriedades/$propertyId/'
      preLoaderRoute: typeof AuthPropriedadesPropertyIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/propriedades/$propertyId/culturas/nova': {
      id: '/_auth/propriedades/$propertyId/culturas/nova'
      path: '/propriedades/$propertyId/culturas/nova'
      fullPath: '/propriedades/$propertyId/culturas/nova'
      preLoaderRoute: typeof AuthPropriedadesPropertyIdCulturasNovaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/propriedades/$propertyId/culturas/$cropId/': {
      id: '/_auth/propriedades/$propertyId/culturas/$cropId/'
      path: '/propriedades/$propertyId/culturas/$cropId'
      fullPath: '/propriedades/$propertyId/culturas/$cropId/'
      preLoaderRoute: typeof AuthPropriedadesPropertyIdCulturasCropIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/propriedades/$propertyId/culturas/$cropId/recomendacao': {
      id: '/_auth/propriedades/$propertyId/culturas/$cropId/recomendacao'
      path: '/propriedades/$propertyId/culturas/$cropId/recomendacao'
      fullPath: '/propriedades/$propertyId/culturas/$cropId/recomendacao'
      preLoaderRoute: typeof AuthPropriedadesPropertyIdCulturasCropIdRecomendacaoRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCulturasRoute: typeof AuthCulturasRoute
  AuthPerfilRoute: typeof AuthPerfilRoute
  AuthPropriedadesNovaRoute: typeof AuthPropriedadesNovaRoute
  AuthPropriedadesIndexRoute: typeof AuthPropriedadesIndexRoute
  AuthPropriedadesPropertyIdIndexRoute: typeof AuthPropriedadesPropertyIdIndexRoute
  AuthPropriedadesPropertyIdCulturasNovaRoute: typeof AuthPropriedadesPropertyIdCulturasNovaRoute
  AuthPropriedadesPropertyIdCulturasCropIdRecomendacaoRoute: typeof AuthPropriedadesPropertyIdCulturasCropIdRecomendacaoRoute
  AuthPropriedadesPropertyIdCulturasCropIdIndexRoute: typeof AuthPropriedadesPropertyIdCulturasCropIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCulturasRoute: AuthCulturasRoute,
  AuthPerfilRoute: AuthPerfilRoute,
  AuthPropriedadesNovaRoute: AuthPropriedadesNovaRoute,
  AuthPropriedadesIndexRoute: AuthPropriedadesIndexRoute,
  AuthPropriedadesPropertyIdIndexRoute: AuthPropriedadesPropertyIdIndexRoute,
  AuthPropriedadesPropertyIdCulturasNovaRoute:
    AuthPropriedadesPropertyIdCulturasNovaRoute,
  AuthPropriedadesPropertyIdCulturasCropIdRecomendacaoRoute:
    AuthPropriedadesPropertyIdCulturasCropIdRecomendacaoRoute,
  AuthPropriedadesPropertyIdCulturasCropIdIndexRoute:
    AuthPropriedadesPropertyIdCulturasCropIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
